load(
    "@fbcode//comms/testinfra:def_test.bzl",
    "rccl_cpp_distributed_unittest",
)
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbcode_macros//build_defs:gpu_cpp_library.bzl", "gpu_cpp_library")

oncall("rccl")

cpp_unittest(
    name = "rccl_logger_unittest",
    srcs = [
        "LoggerTest.cc",
    ],
    preprocessor_flags = ["-DENABLE_META_COLLTRACE"],
    deps = [
        "//comms/rcclx/develop/meta/lib:rccl_logger",
        "//folly/init:init",
    ],
)

cpp_unittest(
    name = "rccl_proxy_trace_unittest",
    srcs = [
        "ProxyTraceTest.cc",
    ],
    deps = [
        "//comms/rcclx/develop/meta/lib:proxy_trace",
    ],
)

gpu_cpp_library(
    name = "rcclx_test_utils",
    srcs = ["RcclxTestUtils.cu"],
    headers = [
        "RcclxTestUtils.h",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gtest",
        "//comms/rcclx:rcclx-dev",  # @manual
        "//comms/testinfra:mpi_test_utils",
        "//comms/utils:checks",
    ],
)

rccl_cpp_distributed_unittest(
    name = "hello_world_test",
    srcs = ["HelloWorldTest.cu"],
    configuration = {
        "nnodes": 1,
        "ppn": 8,
    },
    deps = [
        ":rcclx_test_utils",
        "//comms/utils:cuda_raii",
        "//folly/init:init",
    ],
)

rccl_cpp_distributed_unittest(
    name = "fuse_kernel_test",
    srcs = ["FusekernelTest.cu"],
    configuration = {
        "nnodes": 1,
        "ppn": 8,
    },
    deps = [
        ":rcclx_test_utils",
        "//comms/utils:cuda_raii",
        "//folly/init:init",
    ],
)

cpp_unittest(
    name = "colltrace_utils_tests",
    srcs =
        [
            "CollTraceUtilsTest.cc",
        ],
    deps = [
        "//comms/rcclx/develop/meta/lib:colltrace_utils",
    ],
)
