"""
This file is generated by mgt. Please review and modify for correctness.
For reference, please see https://fburl.com/third-party-metadata.
"""

METADATA = {
    "licenses": [
        "Proprietary",
    ],
    "maintainers": [
        "rccl",
    ],
    "name": "rccl",
    "upstream_address": "https://github.com/ROCmSoftwarePlatform/rccl.git",
    "upstream_hash": "12315c259ac4e24ef3709d37966a69dfdff17f6f",
    "upstream_type": "git",
    "version": "develop",
}
