load("@fbcode//comms/rcclx:rccl_build_config.bzl", "COMMON_COMPILER_FLAGS")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("rccl")

cpp_library(
    name = "rccl_logger",
    srcs = ["ScubaLogger.cc"],
    headers = [
        "Common.h",
        "ScubaLogger.h",
    ],
    compiler_flags = COMMON_COMPILER_FLAGS,
    preferred_linkage = "static",
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//dsi/logger/configs/RcclCollTraceLoggerConfig:logger",
    ],
    exported_deps = [
        "//folly:singleton",
        "//folly/logging:logging",
    ],
)

cpp_library(
    name = "colltrace_utils",
    srcs = ["CollTraceUtils.cc"],
    headers = [
        "CollTraceUtils.h",
        "EventQueue.h",
    ],
    compiler_flags = COMMON_COMPILER_FLAGS,
    preferred_linkage = "static",
    deps = [
        "//common/fbwhoami:fb_who_am_i",
        "//rfe/scubadata:scubadata",
    ],
    exported_deps = [
    ],
)

cpp_library(
    name = "proxy_trace",
    srcs = ["ProxyTrace.cc"],
    headers = [
        "Common.h",
        "ProxyTrace.h",
    ],
    compiler_flags = COMMON_COMPILER_FLAGS,
    preferred_linkage = "static",
    deps = [
        "//folly/debugging/exception_tracer:smart_exception_stack_trace_hooks",  # @manual
    ],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly/logging:logging",
    ],
)
